# Generated by Django 4.2.7 on 2025-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.TextField()),
                ('location', models.TextField()),
                ('capacity', models.IntegerField()),
                ('price_range', models.TextField()),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venue_details',
            },
        ),
    ]
